### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by GEK1** [edumeet/edumeet#1020]
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/usr/local/edumeet/server/node_modules/redis/index.js:342:14)
    at Socket.<anonymous> (/usr/local/edumeet/server/node_modules/redis/index.js:223:14)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}

**Comment by accidentul** [comment]
how did you resolved this issue ?
