### ISSUE TITLE
"digital envelope routines::unsupported" on Node 18 LTS

### ISSUE THREAD

**Issue by MichaelJCole** [edumeet/edumeet#1051]
**Describe the bug**
Similar to https://github.com/edumeet/edumeet/issues/941 

**To Reproduce**
1. Close the repo
2. follow readme to set config files
3. `yarn && yarn build && cd ../server && yarn && yarh build`

```
> $ yarn && yarn build && cd ../server && yarn && yarh build                                                                                           ⬡ 18.14.0 [±master ✓]
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > draft-js-export-html@1.4.1" has unmet peer dependency "immutable@3.x.x".
warning "draft-js-export-html > draft-js-utils@1.4.0" has unmet peer dependency "immutable@3.x.x".
warning " > @typescript-eslint/eslint-plugin@4.25.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning " > @typescript-eslint/parser@4.25.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning " > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1".
warning " > eslint-config-react-app@6.0.0" has unmet peer dependency "eslint@^7.5.0".
warning " > eslint-plugin-flowtype@5.7.2" has unmet peer dependency "eslint@^7.1.0".
warning " > eslint-plugin-import@2.23.3" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0".
warning " > eslint-plugin-jest@24.3.6" has unmet peer dependency "eslint@>=5".
warning " > eslint-plugin-jsx-a11y@6.4.1" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
warning " > eslint-plugin-react@7.23.2" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
warning " > eslint-plugin-react-hooks@4.2.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0".
warning " > eslint-webpack-plugin@2.5.4" has unmet peer dependency "eslint@^7.0.0".
warning " > eslint-webpack-plugin@2.5.4" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > riek@1.1.0" has incorrect peer dependency "react@^0.14.0 || ^15.5.4".
warning " > riek@1.1.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.5.4".
warning " > eslint-import-resolver-typescript@2.4.0" has unmet peer dependency "eslint@*".
[4/4] Building fresh packages...
Done in 34.73s.
yarn run v1.22.19
$ react-scripts build && rm -rf ../server/public && DEST='../server/dist/public' && rm -rf $DEST && mkdir -p $DEST && mv -T build/ $DEST
Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/michael/edumeet/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/michael/edumeet/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/michael/edumeet/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/michael/edumeet/app/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/michael/edumeet/app/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/michael/edumeet/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/michael/edumeet/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/michael/edumeet/app/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/michael/edumeet/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/michael/edumeet/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/michael/edumeet/app/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/michael/edumeet/app/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/michael/edumeet/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/michael/edumeet/app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Expected behavior**
Example should build and run

**Screenshots**

**Branch/Versions:**
Master on today's version

**Server (if available please complete the following information):**
Ubuntu

**Client:**
Didn't get that far

**Additional context**

**Comment by MichaelJCole** [comment]
This appears to be because webpack uses and insecure md4 algo for hashing: https://stackoverflow.com/a/72219174/1483977

That link includes a monkey-patch for the crypto lib to work around it.  Solution is to upgrade webpack.
