### ISSUE TITLE
openID error please help

### ISSUE THREAD

**Issue by jhonforde** [edumeet/edumeet#521]
Error: did not find expected authorization request details in session, req.session["oidc:accounts.google.com"] is undefined
    at /usr/local/src/multiparty-meeting/server/node_modules/openid-client/lib/passport_strategy.js:125:13
    at OpenIDConnectStrategy.authenticate (/usr/local/src/multiparty-meeting/server/node_modules/openid-client/lib/passport_strategy.js:173:5)
    at attempt (/usr/local/src/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/usr/local/src/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at Layer.handle [as handle_request] (/usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/index.js:335:12)

When I login with OpenID I get the above errors please help! Configuration file:

	// Auth conf
	
	auth :
	{
		lti :
		{
			consumerKey    : 'key',
			consumerSecret : 'secret'
		},
		oidc:
		{
			// The issuer URL for OpenID Connect discovery
			// The OpenID Provider Configuration Document
			// could be discovered on:
			// issuerURL + '/.well-known/openid-configuration'
			issuerURL     : 'https://accounts.google.com/',
			clientOptions :
			{

				client_id       : 'xxxxxxxxx.apps.googleusercontent.com',
				client_secret   : 'xxxxxxxxxxx',
				scope           : 'openid email profile',
				redirect_uri    : 'https://xxxxx/auth/callback'
				
				// where client.example.com is your multiparty meeting server
				
			}
		}
	},

**Comment by misi** [comment]
Check your redis and cookie config because, the error is about that 
before the site redirects to issuerURL(accounts.google.com) is saves the session to redis based and issues a cookie 
after login when google redirects back we try based on the cookie restore the saved session from the redis.
The issue according the error that the session is not found in in the redis. 

e.g. Try to debug more, and try to empty your browser cookies..

**Comment by roman-drozd-it** [comment]
No response much more than 1 month. Closed.
