### ISSUE TITLE
installation Time  Error

### ISSUE THREAD

**Issue by livingloves** [edumeet/edumeet#537]
please Help ME

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> clang-tools-prebuilt@0.1.4 postinstall C:\Users\Souma\Documents\edumeet\server\node_modules\clang-tools-prebuilt
> node install.js

C:\Users\Souma\Documents\edumeet\server\node_modules\clang-tools-prebuilt\install.js:24
if (!platforms[platform]) throw new Error('Unknown platform: ' + platform)
                          ^

Error: Unknown platform: win32
    at Object.<anonymous> (C:\Users\Souma\Documents\edumeet\server\node_modules\clang-tools-prebuilt\install.js:24:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

> mediasoup@3.6.18 postinstall C:\Users\Souma\Documents\edumeet\server\node_modules\mediasoup
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: python ./worker/scripts/configure.py --format=msvs -R mediasoup-worker
npm WARN notsup Unsupported engine for xmlbuilder@2.4.6: wanted: {"node":"0.8.x || 0.10.x || 0.11.x  || 1.0.x"} (current: {"node":"10.22.0","npm":"6.14.6"})
npm WARN notsup Not compatible with your version of node/npm: xmlbuilder@2.4.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: clang-tools-prebuilt@0.1.4 (node_modules\clang-tools-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: clang-tools-prebuilt@0.1.4 postinstall: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.6.18 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@3.6.18 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Souma\AppData\Roaming\npm-cache\_logs\2020-09-07T13_31_39_841Z-debug.log

C:\Users\Souma\Documents\edumeet\server>npm start

> multiparty-meeting-server@3.3.0 start C:\Users\Souma\Documents\edumeet\server
> node server.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'mediasoup'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Souma\Documents\edumeet\server\server.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multiparty-meeting-server@3.3.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multiparty-meeting-server@3.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Souma\AppData\Roaming\npm-cache\_logs\2020-09-07T13_33_07_602Z-debug.log

**Comment by misi** [comment]
Something went wrong with your install. It should work. 
Please give more details about youre OS, which branch, version etc.
Try to delete all and checkout code again and try a clean install. If not helps let me know more details.
