### ISSUE TITLE
Bug in local auth

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#600]
1. For local auth line 509 in server.js should be
state = JSON.parse(base64.decode(req.query.state));

2. There is a bug with the session sharing between express and socket.io, but only when logging in from lobby:
how to reproduce:
- by logget out and clear site data
- go to room, click join, by halted in lobby
- now login to join permissions to join room
- press F5 and join room again - you get again stopped in the lobby

On the other hand:
- by logget out and clear site data
- go to room
- now login to join permissions from JoinDialog
- click join, and enter room as you are logged in
- press F5 and join room again - you can enter without having to login again

It seams that if the login happens when a socket.io connection is already in place, the fact that the user is logged in is not saved in session. 

@misi

**Comment by misi** [comment]
@Astagor @roman-drozd-it 
1. We store state in session not in URL parameter. So it is right as it is.
2. I guess it is general issue, because we don't get auth state from server but from local state, and this causing the  issue. and so it is not special for Local Auth but it is general, so title little bit misleading.

I will try to restore the previous way where if we don't know the server state we default to logged out, 
or if it is easy make hook to get from server the auth state and set according the store logged in value.

**Comment by Astagor** [comment]
As for 1 it was to late in the night, it should be:
state=JSON.parse(base64.decode(req.session.authState));

**Comment by misi** [comment]
AFAIU we don't need to decode encode objects that are stored in session so just stored it without encoding

**Comment by Astagor** [comment]
OK.
I got a new error
`2020-11-03T10:19:56.754Z edumeet-server:ERROR Express error handler dump with tracking ID: 3585f3e4-f1b3-465c-94d8-2721e346aba6, error dump: TypeError: Cannot destructure property `peerId` of 'undefined' or 'null'. at app.all (/usr/local/src/multiparty-meeting/server/server.js:560:32) at Layer.handle [as handle_request] (/usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/route.js:137:13) at complete (/usr/local/src/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:268:13) at /usr/local/src/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:275:15 at pass (/usr/local/src/multiparty-meeting/server/node_modules/passport/lib/authenticator.js:431:14) at Authenticator.transformAuthInfo (/usr/local/src/multiparty-meeting/server/node_modules/passport/lib/authenticator.js:453:5) at /usr/local/src/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:272:22 at /usr/local/src/multiparty-meeting/server/node_modules/passport/lib/http/request.js:52:7 at /usr/local/src/multiparty-meeting/server/node_modules/passport/lib/sessionmanager.js:26:5`

I login, enter a room and then 3 or 4 times logout and login, while in the room. A login attempt causes the problem. It seams as if the req.session is not defined. How this can happen hmm. Maybe after we destroy it in the logout, it does not reactivate?

**Comment by misi** [comment]
@Astagor  Can you say which commit you used during the error above?

**Comment by Astagor** [comment]
The current develop.

**Comment by Astagor** [comment]
But it only happens when, you do it quickly with autofill of user and password.

**Comment by misi** [comment]
I 

> OK.
> I got a new error
> `2020-11-03T10:19:56.754Z edumeet-server:ERROR Express error handler dump with tracking ID: 3585f3e4-f1b3-465c-94d8-2721e346aba6, error dump: TypeError: Cannot destructure property `peerId` of 'undefined' or 'null'. at app.all (/usr/local/src/multiparty-meeting/server/server.js:560:32) at Layer.handle [as handle_request] (/usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/local/src/multiparty-meeting/server/node_modules/express/lib/router/route.js:137:13) at complete (/usr/local/src/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:268:13) at /usr/local/src/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:275:15 at pass (/usr/local/src/multiparty-meeting/server/node_modules/passport/lib/authenticator.js:431:14) at Authenticator.transformAuthInfo (/usr/local/src/multiparty-meeting/server/node_modules/passport/lib/authenticator.js:453:5) at /usr/local/src/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:272:22 at /usr/local/src/multiparty-meeting/server/node_modules/passport/lib/http/request.js:52:7 at /usr/local/src/multiparty-meeting/server/node_modules/passport/lib/sessionmanager.js:26:5`
> 
> I login, enter a room and then 3 or 4 times logout and login quickly (prefilled form), while in the room. A login attempt causes the problem. It seams as if the req.session is not defined. How this can happen hmm. Maybe after we destroy it in the logout, it does not reactivate?

I can't reproduce it. Can you demo to me?

**Comment by misi** [comment]
There was issue that in case of failure redirected to /auth/login without any query params. It is fixed in commits: 

* Added check for query params: 648fbe847a71bdee39fee42eb9d58ebb52fff6e5
* Handle empty state: 7095d6b98e620dfdba477ec518dd69741db5dafb
(The RoomId => roomId typo is fixed in other commit)

**Comment by gunnurafi** [comment]
how to setup admin portal in edumeet please help me out

**Comment by Astagor** [comment]
I did test it, yes it works, and it is more intuitive. But the main problem, the synchronization of  sessions is still there. Solving it would allow for seamless experience. Now depending on which screen you have logged in (name choosing or lobby) after F5 the reaction of the system is different. 

And I found one more error, also due to the express session and socket IO session being out of sync. In some cases LOGOUT when in room does not work properly as req.session.peerId is undefined. When you click logout, the UI shows you have logged out, but you do not lose your roles. As a temp solution in RoomClient I have put peerId in the URL for logout. This way I do not read the peerId from the session but from the request.

But these all these errors and hacks are caused by the root problem, the socket IO session being out of sync with express session.

**Comment by manalejandro** [comment]
I have same issue when do local strategy auth, using the official Dockerfile. The problem is `state` variable is `undefined` in server.js
```
edumeet-server:ERROR Express error handler dump with tracking ID: b1185ff7-208f-41b1-83f0-c31c570140b4, error dump: TypeError: Cannot destructure property `peerId` of 'un
defined' or 'null'. at app.all (/opt/edumeet/server/server.js:515:32) at Layer.handle [as handle_request] (/opt/edumeet/server/node_modules/express/lib/router/layer.js:95:5) at next (/opt/edu
meet/server/node_modules/express/lib/router/route.js:137:13) at complete (/opt/edumeet/server/node_modules/passport/lib/middleware/authenticate.js:268:13) at /opt/edumeet/server/node_modules/
passport/lib/middleware/authenticate.js:275:15 at pass (/opt/edumeet/server/node_modules/passport/lib/authenticator.js:431:14) at Authenticator.transformAuthInfo (/opt/edumeet/server/node_mod
ules/passport/lib/authenticator.js:453:5) at /opt/edumeet/server/node_modules/passport/lib/middleware/authenticate.js:272:22 at /opt/edumeet/server/node_modules/passport/lib/http/request.js:5
2:7 at /opt/edumeet/server/node_modules/passport/lib/sessionmanager.js:26:5 +0ms
```
