### ISSUE TITLE
Problem with port listening. Service is running. No access. 

### ISSUE THREAD

**Issue by Aleeeeeeeex** [edumeet/edumeet#646]
Any idea what i am missing? Only thing i did not setup is tls.. (dont know how.. lol) But guess that should not prevent it from starting and running? 

Running on Azure Ubuntu server. 
Node: v13.14.0
npm: 6.14.4
Service is starting, no errors.
```
WebinarVMRoot@WebinarVM:/home/edumeet/server$ systemctl status edumeet
● edumeet.service - edumeet is a audio / video meeting service running in the browser and powered by webRTC
   Loaded: loaded (/etc/systemd/system/edumeet.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-12-09 19:04:48 UTC; 2min 40s ago
 Main PID: 3563 (node)
    Tasks: 7 (limit: 4915)
   CGroup: /system.slice/edumeet.service
           └─3563 edumeet-server

Dec 09 19:04:48 WebinarVM systemd[1]: Started edumeet is a audio / video meeting service running in the browser and powered by webRTC.
Dec 09 19:04:49 WebinarVM server.js[3563]: - process.env.DEBUG: undefined
Dec 09 19:04:49 WebinarVM server.js[3563]: - config.mediasoup.worker.logLevel: warn
Dec 09 19:04:49 sWebinarVM server.js[3563]: - config.mediasoup.worker.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp' ]

```

Does not look like it is listening to ports?
```
root@WebinarVM:/home/edumeet/server# sudo ss -tulw
Netid            State              Recv-Q             Send-Q                           Local Address:Port                                Peer Address:Port
icmp6            UNCONN             0                  0                                       *%eth0:ipv6-icmp                                      *:*
udp              UNCONN             0                  0                                127.0.0.53%lo:domain                                   0.0.0.0:*
udp              UNCONN             0                  0                                10.0.2.4%eth0:bootpc                                   0.0.0.0:*
tcp              LISTEN             0                  511                                  127.0.0.1:6379                                     0.0.0.0:*
tcp              LISTEN             0                  128                              127.0.0.53%lo:domain                                   0.0.0.0:*
tcp              LISTEN             0                  128                                    0.0.0.0:ssh                                      0.0.0.0:*
tcp              LISTEN             0                  511                                      [::1]:6379                                        [::]:*
tcp              LISTEN             0                  128                                       [::]:ssh                                         [::]:*

```

Azure ports is setup:
![image](https://user-images.githubusercontent.com/22255599/101673893-0deb7580-3a58-11eb-8d67-5116d86b7de1.png)

Config file: (Updated local and public ip) 
// listeningHost: 'localhost', is commented out as default. 

```
 listenIps :

                        [
                                // change 192.0.2.1 IPv4 to your server's IPv4 address!!
                                { ip: '10.0.2.4', announcedIp: '51.13.72.***' }

                                // Can have multiple listening interfaces
                                // change 2001:DB8::1 IPv6 to your server's IPv6 address!!
                                // { ip: '2001:DB8::1', announcedIp: null }
                        ],
```

**Comment by sabkaraja** [comment]
seems similar to this issue #644

**Comment by Aleeeeeeeex** [comment]
i tried to install mediasoup again.. but i dont face same error.. 

If i run export DEBUG=*; npm start without sudo i get this message.. when i do it with root i dont get any error.

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at runHttpsServer (/home/edumeet/server/server.js:630:21)
    at run (/home/edumeet/server/server.js:159:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edumeet-server@3.3.4 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edumeet-server@3.3.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/TankevirusWebinarVMRoot/.npm/_logs/2020-12-10T06_35_14_482Z-debug.log

```

Running as root to get access to port :80 according to online guides. 
```
root@WebinarVM:/home/edumeet/server# export DEBUG=*; npm start

> edumeet-server@3.3.4 start /home/edumeet/server
> node server.js

- process.env.DEBUG: *
- config.mediasoup.worker.logLevel: warn
- config.mediasoup.worker.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp' ]
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +0ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +1ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/home/edumeet/server/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +0ms
  express:router:layer new '/' +1ms
  express:router use '/' expressInit +0ms
  express:router:layer new '/' +0ms
  express:router use '/' hsts +0ms
  express:router:layer new '/' +0ms
  express:router use '/' cookieParser +1ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +0ms
  express:router:layer new '/' +0ms
  express:router use '/' urlencodedParser +1ms
  express:router:layer new '/' +0ms
  express:router use '/' session +0ms
  express:router:layer new '/' +0ms
  edumeet-server:WARN Auth is not configured properly! +0ms
  edumeet-server:INFO running 2 mediasoup Workers... +0ms
  mediasoup createWorker() +0ms
  mediasoup:Worker constructor() +0ms
  mediasoup:Worker spawning worker process: /home/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999 +0ms
  mediasoup:Channel constructor() +0ms
  mediasoup:PayloadChannel constructor() +0ms
  mediasoup:Worker worker process running [pid:3766] +19ms
  mediasoup createWorker() +19ms
  mediasoup:Worker constructor() +0ms
  mediasoup:Worker spawning worker process: /home/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999 +0ms
  mediasoup:Channel constructor() +17ms
  mediasoup:PayloadChannel constructor() +16ms
  mediasoup:Worker worker process running [pid:3768] +15ms
  express:router use '/' compression +38ms
  express:router:layer new '/' +0ms
  express:router use '/.well-known/acme-challenge' serveStatic +1ms
  express:router:layer new '/.well-known/acme-challenge' +0ms
  express:router:route new '*' +0ms
  express:router:layer new '*' +0ms
  express:router:route acl '*' +0ms
  express:router:layer new '/' +1ms
  express:router:route bind '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route checkout '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route connect '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route copy '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route delete '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '*' +1ms
  express:router:layer new '/' +0ms
  express:router:route head '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route link '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route lock '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route m-search '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route merge '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route mkactivity '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route mkcalendar '*' +0ms
  express:router:layer new '/' +1ms
  express:router:route mkcol '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route move '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route notify '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route options '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route patch '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route propfind '*' +0ms
  express:router:layer new '/' +1ms
  express:router:route proppatch '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route purge '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route rebind '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route report '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route search '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route source '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route subscribe '*' +0ms
  express:router:layer new '/' +1ms
  express:router:route trace '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route unbind '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route unlink '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route unlock '*' +0ms
  express:router:layer new '/' +0ms
  express:router:route unsubscribe '*' +0ms
  express:router:layer new '/' +0ms
  express:router use '/' serveStatic +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  spdy:server server init secure=1 +0ms
  socket.io:server initializing namespace / +0ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +0ms
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +0ms
  socket.io:server creating engine.io instance with opts {"cookie":false,"path":"/socket.io","initialPacket":["0"]} +1ms
  socket.io:server attaching client serving req handler +7ms
  express-socket.io-session Creating socket.io middleware +0ms
  socket.io:namespace removing initial packet +0ms
  express:router use '/' errorHandler +38ms
  express:router:layer new '/' +0ms
```

Normally i just start the service without any error messages.. just not listen to the port i guess?

Is debian a better choice?

**Comment by Aleeeeeeeex** [comment]
I see in docs to not run as root.. But it gives me error when i do it due to not allowed to use port 80:
I added this to remove the port complaining.. 
`
sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\``
`

I get no errors on the rebug after this, but still no access.. 

So i think it is enything about mapping

**Comment by so010** [comment]
In general: "don't switch users installing and running the service" if in doubt reinstall or use `chown -r`/  `chgrp -r` on whole directory.

The service will of course run as root but it's a bad idea to do that.
Non-root-users can't run the service on ports below 1024 out of the box - you have to adjust:
- Run the service via systemd by using the service file https://github.com/edumeet/edumeet/blob/master/edumeet.service
- OR run the service on higher ports and in production redirect with firewall rules to port 80/443 (eg. iptables redirect)

**Comment by Aleeeeeeeex** [comment]
Installed all again on clean VM with help. Works now. Thanks for responses.
