### ISSUE TITLE
Error unable to access room

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#700]
Hi,

yesterday we had a problem that occurred on tow of our servers. Problem manifested that we were unable to access a room on those servers. In the error log we got this:

```
2021-02-22T10:25:54.910Z mediasoup:ERROR:Channel [pid:18300 RTC::Router::GetProducerFromInternal() | throwing MediaSoupError: Producer not found
2021-02-22T10:28:08.925Z edumeet-server:ERROR:Room "request" failed [error:"Error: Peer already joined at Room._handleSocketRequest (/usr/local/src/edumeet/server/lib/Room.js:835:12) at Socket.<anonymous> (/usr/local/src/edumeet/server/lib/Room.js:759:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:485:12) at /usr/local/src/edumeet/server/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:79:11)"]
```

```
2021-02-22T12:20:10.815Z engine:polling closing
2021-02-22T12:20:10.815Z engine:polling transport not writable - buffering orderly close
2021-02-22T12:20:10.834Z engine:polling closing
2021-02-22T12:20:10.834Z engine:polling transport not writable - buffering orderly close
2021-02-22T12:20:10.855Z engine:polling closing
```
I haven't found if this error was reported or fixed in dev branch so I'm reporting it.

**Comment by so010** [comment]
This occurred just in one specific room?

**Comment by zmartinovic** [comment]
No, it occured on all rooms on one server. But in the meantime we've upgraded to latest devepol so I hope it won't happen again :)
