### ISSUE TITLE
Error on LOW Resolution

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#763]
Dear Team,

Server: Ubuntu 18.04 LTS, Branch: Latest Develop
Client: MacBook Air, Chrome Version 89.0.4389.114

When changing the video resolution to Low i am getting error **an error occurred while accessing your camera**.
This issue occurring after updating to latest pull 

Thanks

**Comment by so010** [comment]
Can reproduce this:

edumeet:ERROR:RoomClient updateWebcam() [error:"DOMException: Failed to execute 'addTransceiver' on 'RTCPeerConnection': Attempted to set an unimplemented parameter of RtpParameters.
    at n.<anonymous> (https://letsmeet.no/static/js/11.b8e10ec6.chunk.js:2:631295)
    at l (https://letsmeet.no/static/js/11.b8e10ec6.chunk.js:2:560430)
    at Generator._invoke (https://letsmeet.no/static/js/11.b8e10ec6.chunk.js:2:560218)
    at Generator.next (https://letsmeet.no/static/js/11.b8e10ec6.chunk.js:2:560855)
    at n (https://letsmeet.no/static/js/11.b8e10ec6.chunk.js:2:24423)
    at s (https://letsmeet.no/static/js/11.b8e10ec6.chunk.js:2:24634)
    at https://letsmeet.no/static/js/11.b8e10ec6.chunk.js:2:24693
    at new Promise (<anonymous>)
    at n.<anonymous> (https://letsmeet.no/static/js/11.b8e10ec6.chunk.js:2:24574)
    at n.<anonymous> (https://letsmeet.no/static/js/11.b8e10ec6.chunk.js:2:633064)"] +0ms
