### ISSUE TITLE
Issue with load

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#874]
Dear Team,

Server: 
OS: ubuntu 18.04
Hosting Provider: AWS
CPU: 16vCPU
Server CPU Load during the session: 30 percent
Server and APP are running in different hosts

client:

Google Chrome Version 90 and above 
Network  Latency : less than 50ms
CPU usage : Not more than 70 percent

we have conducted a VC Session with more than 200 participants with LASTN=5 and Mobile LASTN=1 once login to the session i dont hear anyone at all and all the options seems behaving weird and there are disconnections too.
Unmute and other options wont work at all clicking one option opens something else   also below are the continual error running logs on the server. 
almost all people joined the meeting with Audio and video mute  
All participants having the same issue and finally switched over to zoom meeting

```
Jun 12 09:19:39 ip-10-0-1-142 server.js[439697]: 2021-06-12T09:19:39.774Z edumeet-server:ERROR:Room "request" failed [error:"Error: Peer not yet joined at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/lib/Room.js:1269:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 12 09:19:40 ip-10-0-1-142 server.js[439697]: 2021-06-12T09:19:40.262Z edumeet-server:ERROR:Room "request" failed [error:"Error: Peer not yet joined at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/lib/Room.js:1250:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 12 09:19:40 ip-10-0-1-142 server.js[439697]: 2021-06-12T09:19:40.263Z edumeet-server:ERROR:Room "request" failed [error:"Error: Peer not yet joined at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/lib/Room.js:1269:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 12 09:19:40 ip-10-0-1-142 server.js[439697]: 2021-06-12T09:19:40.449Z edumeet-server:ERROR:Room "request" failed [error:"NotFoundInMediasoupError: consumer with id "3248da8c-f671-4e41-bfa0-4db56a9d7737" not found at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/lib/Room.js:1275:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 12 09:19:41 ip-10-0-1-142 server.js[439697]: 2021-06-12T09:19:41.306Z edumeet-server:ERROR:Room "request" failed [error:"NotFoundInMediasoupError: consumer with id "11be91aa-feba-4b0e-93c1-2726eb5cc864" not found at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/lib/Room.js:1275:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 12 09:19:41 ip-10-0-1-142 server.js[439697]: 2021-06-12T09:19:41.824Z edumeet-server:ERROR:Room "request" failed [error:"NotFoundInMediasoupError: consumer with id "8c48bc6a-6464-4e9d-a73c-1829804ff0ba" not found at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/lib/Room.js:1275:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
```

![Screenshot 2021-06-12 at 5 04 35 PM](https://user-images.githubusercontent.com/65006646/121775226-f24a5e80-cba3-11eb-8a86-32380b53f129.png)

++ #862

**Comment by Alex-YddeR** [comment]
we have again conducted meeting again with more than 200 users login from mobiles, desktops and laptops all are real participants like last time we faced same issue like before, in UI there is a flow of notifications of user join and sometimes **error on server request** 

Server:
OS: ubuntu 18.04
Hosting Provider: AWS
CPU: 16vCPU
Ram Usage:  3GB out of 32GB
Server CPU Load during the session: 30 percent
Server and APP are running in different hosts

client:

Google Chrome Version 90 and above
Network Latency : less than 50ms
CPU usage : Not more than 70 percent
LAST N=5 and Mobile LASTN=1


below is the same log found

Jun 23 06:59:25 ip-10-0-1-142 server.js[601]: 2021-06-23T06:59:25.741Z edumeet-server:ERROR:Room "request" failed [error:"NotFoundInMediasoupError: consumer with id "b0f627af-47fe-4d8b-bb18-61cfdf310c57" not found at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/server/lib/Room.js:1275:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 23 06:59:25 ip-10-0-1-142 server.js[601]: 2021-06-23T06:59:25.796Z edumeet-server:ERROR:Room "request" failed [error:"NotFoundInMediasoupError: consumer with id "215172ab-0721-44cc-93da-9166ee99d503" not found at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/server/lib/Room.js:1275:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 23 06:59:25 ip-10-0-1-142 server.js[601]: 2021-06-23T06:59:25.898Z edumeet-server:ERROR:Room "request" failed [error:"NotFoundInMediasoupError: consumer with id "e59d2fb4-cfe1-4961-a430-4275a1e1576d" not found at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/server/lib/Room.js:1275:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 23 06:59:25 ip-10-0-1-142 server.js[601]: 2021-06-23T06:59:25.905Z edumeet-server:ERROR:Room "request" failed [error:"NotFoundInMediasoupError: consumer with id "f7779349-9529-4c1a-8541-91fc3282e81e" not found at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/server/lib/Room.js:1275:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 23 06:59:25 ip-10-0-1-142 server.js[601]: 2021-06-23T06:59:25.927Z edumeet-server:ERROR:Room "request" failed [error:"NotFoundInMediasoupError: consumer with id "5d8fd94d-06b8-48c1-9b57-9a21e9a58904" not found at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/server/lib/Room.js:1275:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:75:11)"]
Jun 23 06:59:25 ip-10-0-1-142 server.js[601]: 2021-06-23T06:59:25.973Z edumeet-server:ERROR:Room "request" failed [error:"NotFoundInMediasoupError: consumer with id "14f99a0b-8c66-4e7e-8360-3d27662b0425" not found at Room._handleSocketRequest (/var/lib/jenkins/workspace/edumeet/server/lib/Room.js:1275:12) at Socket.<anonymous> (/var/lib/jenkins/workspace/edumeet/lib/Room.js:809:9) at Socket.emit (events.js:315:20) at Socket.EventEmitter.emit (domain.js:467:12) at /var/lib/jenkins/workspace/edumeet/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queue


Again it is shifted to Google meet

Thanks
Alex

**Comment by Alex-YddeR** [comment]
Anyone is able to do load test with more than 100 participants with LASTN 5, i see there are drops in connections and after disconnection and connect back it takes so much time to get audio from the participants and also enabling audio mute takes so much time to respond.


Thanks
