### ISSUE TITLE
Can't build on Node.js v17.3.1

### ISSUE THREAD

**Issue by piranna** [edumeet/edumeet#941]
I've just cloned the project from scratch and followed the install instructions, but when building it I get the next error:

```
[piranna@PRO2:~/github/Mafalda/EduMeet-Mafalda/app]
 (develop) > npm run build

> edumeet@3.4.0 build
> react-scripts build && rm -rf ../server/public && DEST='../server/dist/public' && rm -rf $DEST && mkdir -p $DEST && mv -T build/ $DEST

Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/piranna/github/Mafalda/EduMeet-Mafalda/app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.1
```

Maybe there are some backwards incompatible changes on Node.js v17 regarding to supported crypto algorythms? Or should EduMeet check for that situation itself?

**Comment by piranna** [comment]
https://github.com/webpack/webpack/issues/14532#issuecomment-947012063

Ok, confirmed: it's a Node.js v17 issue related to upgrade to a safer version of OpenSSL.

**Comment by roman-drozd-it** [comment]
@piranna We don't support `node 17.x` yet.

**Comment by piranna** [comment]
It's an upcoming version... I can understand it of unmaintained ones, but for future ones? I don't understand why it got closed.

**Comment by piranna** [comment]
Problem still happens, and the same with Node.js v18, that's the new LTS.

**Comment by piranna** [comment]
Problem still present with Node.js v18.12.1
